### ISSUE TITLE
split exporter code

### ISSUE THREAD

**Issue by greenpau** [greenpau/ovn_exporter#1]
@sdstack wrote:

> >
> > For the people interested in the topic of monitoring OVN, please check out Prometheus exporter for OVN: ovn_exporter repo on github.
> >
> > Tried including the metrics I thought relevant for the monitoring of OVN clustering/raft. Another helpful metric is "log_event_count". It is the number of recorded log messages associated with an OVN component by log severity level and source.
> >
> > Anyone else using Prometheus for OVN monitoring? Statsd?
> >
> 
> Thanks for this. I'm use prometheus to monitor ovn/ovs. But i'm
> already have some app that also control ovn (CMS).. So can you split
> you monitoring exported for two parts. First - exporter that provide
> http.Handler, and second - main.go that creates standalone binary and
> use http.Handler?
> In this case users as me - can use you package with own http server
> and integrate exporter in app, and other - can run standalone binary.
> What do you think?
> P.S. I'm already have such splitting for libvirt exporter.

**Comment by greenpau** [comment]
@sdstack, do you have the libvirt exporter published, so I can take a look?

**Comment by vtolstov** [comment]
check this please, https://github.com/sdstack/prometheus-libvirt

**Comment by greenpau** [comment]
@vtolstov , I refactored it per https://github.com/golang-standards/project-layout.

**Comment by vtolstov** [comment]
Thanks!
