### ISSUE TITLE
ovn-exporter fails with: "interface conversion: interface {} is uint8, not string" when hitting /metrics

### ISSUE THREAD

**Issue by kaivanov** [greenpau/ovn_exporter#4]
`
May 28 17:41:18 use1-dcs-ctl-1-infra-ovn-container-a591f530 ovn-exporter[83325]: time="2021-05-28T17:41:18Z" level=debug msg="dee9da30-260a-4f7c-90f8-e88f56266cd2: GatherMetrics() calls GetLogicalSwitchPorts()" source="ovn_exporter.go:591"
May 28 17:41:18 use1-dcs-ctl-1-infra-ovn-container-a591f530 ovn-exporter[83325]: panic: interface conversion: interface {} is uint8, not string
May 28 17:41:18 use1-dcs-ctl-1-infra-ovn-container-a591f530 ovn-exporter[83325]: goroutine 6 [running]:
May 28 17:41:18 use1-dcs-ctl-1-infra-ovn-container-a591f530 ovn-exporter[83325]: github.com/greenpau/ovsdb.(*Row).GetColumnValue(0xc0002248d8, 0xaa1b1f, 0x9, 0xc0000dffb0, 0x9e27e0, 0xc000268360, 0xc000194a00, 0x11, 0x0, 0x0)
May 28 17:41:18 use1-dcs-ctl-1-infra-ovn-container-a591f530 ovn-exporter[83325]:         /go/pkg/mod/github.com/greenpau/ovsdb@v0.0.0-20181114004433-3582b85e8968/result.go:56 +0x24be
May 28 17:41:18 use1-dcs-ctl-1-infra-ovn-container-a591f530 ovn-exporter[83325]: github.com/greenpau/ovsdb.(*OvnClient).GetLogicalSwitchPorts(0xc000212e00, 0x31, 0xc000225890, 0x1, 0x1, 0x2)
May 28 17:41:18 use1-dcs-ctl-1-infra-ovn-container-a591f530 ovn-exporter[83325]:         /go/pkg/mod/github.com/greenpau/ovsdb@v0.0.0-20181114004433-3582b85e8968/ovn_logical_switch_port.go:85 +0x417
May 28 17:41:18 use1-dcs-ctl-1-infra-ovn-container-a591f530 ovn-exporter[83325]: github.com/greenpau/ovn_exporter/pkg/ovn_exporter.(*Exporter).GatherMetrics(0xc0001f0e00)
May 28 17:41:18 use1-dcs-ctl-1-infra-ovn-container-a591f530 ovn-exporter[83325]:         /go/github.com/greenpau/ovn_exporter/pkg/ovn_exporter/ovn_exporter.go:592 +0x1f10
May 28 17:41:18 use1-dcs-ctl-1-infra-ovn-container-a591f530 ovn-exporter[83325]: github.com/greenpau/ovn_exporter/pkg/ovn_exporter.(*Exporter).Collect(0xc0001f0e00, 0xc000160de0)
May 28 17:41:18 use1-dcs-ctl-1-infra-ovn-container-a591f530 ovn-exporter[83325]:         /go/github.com/greenpau/ovn_exporter/pkg/ovn_exporter/ovn_exporter.go:368 +0x43
May 28 17:41:18 use1-dcs-ctl-1-infra-ovn-container-a591f530 ovn-exporter[83325]: github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
May 28 17:41:18 use1-dcs-ctl-1-infra-ovn-container-a591f530 ovn-exporter[83325]:         /go/pkg/mod/github.com/prometheus/client_golang@v1.8.0/prometheus/registry.go:444 +0x19d
May 28 17:41:18 use1-dcs-ctl-1-infra-ovn-container-a591f530 ovn-exporter[83325]: created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
May 28 17:41:18 use1-dcs-ctl-1-infra-ovn-container-a591f530 ovn-exporter[83325]:         /go/pkg/mod/github.com/prometheus/client_golang@v1.8.0/prometheus/registry.go:536 +0xdf8
May 28 17:41:18 use1-dcs-ctl-1-infra-ovn-container-a591f530 systemd[1]: ovn-exporter.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 28 17:41:18 use1-dcs-ctl-1-infra-ovn-container-a591f530 systemd[1]: ovn-exporter.service: Failed with result 'exit-code'.
`

**Comment by stefreak** [comment]
@greenpau I think this has now been resolved as well with #6

**Comment by greenpau** [comment]
> @greenpau I think this has now been resolved as well with #6

@stefreak , awesome! Kudos to @rnurgaliyev 

@kaivanov , please test.
